name: twitter_api
description: TinkerHub SaturdayHackNight Twitter API Project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dart_twitter_api: ^0.3.4
  dartz: ^0.9.2
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.1
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
